[package]
name = "batty"
version = "0.6.0"
edition = "2021"
description = "A cat clone with syntax highlighting, git integration, and Rhai support"
license = "MIT"

[dependencies]
clap          = { version = "4", features = ["derive", "env"] }
syntect       = { version = "5", default-features = false, features = ["parsing", "regex-onig", "yaml-load"] }
two-face      = "0.4"
git2          = { version = "0.19", default-features = false }
pager         = "0.16"
anstyle       = "1"
anstyle-query = "1"
dirs          = "5"
anyhow        = "1"
crossterm = "0.28"
toml = { version = "0.8", default-features = false, features = ["parse"] }
termimad = "0.34"
unicode-width = "0.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = "3"

[profile.release]
opt-level     = "z"
lto           = true
codegen-units = 1
strip         = true
panic         = "abort"
